#! /bin/bash
currentTodoList=$TODOPATH/$(ls $TODOPATH | grep $(date "+%m-%d-%Y"))
if [ "$1" = "add" ]
then
  echo $"- "$2 >> $currentTodoList
  cat $currentTodoList || echo "Error: Crontab failure, todolist not created    "
elif [ "$1" = "c" ]
then
  python addCompleted.py $currentTodoList "$2"
  cat $currentTodoList || echo "Error: Crontab failure, todolist not created    "
else
  cat $currentTodoList || echo "Error: Crontab failure, todolist not created"
fi

